#!/bin/bash
#
# d-edit: Use dmenu to open and edit a file from a given list.

# Global variables:
FILES1=${1:-"/home/sean/.config"}
FILES2=${1:-"/home/sean/.local/scripts"}
FILES3=${1:-"/home/sean/.dotfiles/programms/dwm"}
DMENU='dmenu -l 30 -i'
EDITOR='gnome-terminal -e nano'
# Show list of options
choice=$(ls -a "${FILES1}" | $DMENU -p "File to edit:")

if [ $choice ]; then
    $EDITOR ${FILES}/${choice}
fi
