#!/bin/sh


SAEDITOR="emacsclient -c -a emacs"

declare -a options=(

"zshrc - $HOME/.config/zsh/.zshrc"
"bashrc - $HOME/.bashrc"
"dwm-config - $HOME/.dotfiles/bin/dwm/config.def.h"
"dwm-c -$HOME/.dotfiles/bin/dwm/dwm.c"
"dwm-blocks - $HOME/.dotfiles/bin/dwmblocks/blocks.def.h"


"quit"
)

choice=$(printf '%s\n' "${options[@]}" | dmenu -i -l 20 -p 'Edit config:')

if [[ "$choice" == "quit" ]]; then
    echo "Terminated" && exit 1

elif [ "$choice" ];then
    cfg=$(printf '%s\n' "${choice}" |awk '{print $NF}')
    $SAEDITOR "$cfg"

else
    echo "Terminated." && exit 1
fi
